apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "light-operator.fullname" . }}
  labels:
    {{- include "light-operator.labels" . | nindent 4 }}
data:
  config.local.yaml: |-
    {{- .Values.configOverride | toYaml | nindent 4 }}
