apiVersion: v1
kind: Secret
metadata:
  name: {{ include "light-operator.fullname" . }}
  labels:
    {{- include "light-operator.labels" . | nindent 4 }}
data:
  LO__SMART_HOME__SMARTTHINGS__API_KEY: {{ .Values.smarthome.smartthings.apiKey | default "" | b64enc | quote }}

