name: Image Build

on:
  workflow_dispatch:
  push:
    tags: [ '*' ]


env:
  CARGO_TERM_COLOR: always

jobs:
  images:
    name: Create container images
    runs-on: ubuntu-22.04

    container:
      image: ubuntu:23.10
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    # Install required dependencies for cross-platform image builds
    - run: |-
        apt-get update
        apt-get install -y qemu-user-static buildah binfmt-support curl

    - uses: dtolnay/rust-toolchain@stable

    # Build images
    - name: Buildah
      id: buildah
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/luryus/light-operator
        tags: ${{ github.sha }} ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name }}
        containerfiles: |
          ./Containerfile
        platforms: linux/amd64, linux/aarch64
    
    # Push images
    - name: Push images
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.buildah.outputs.image }}
        tags: ${{ steps.buildah.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}